### ISSUE TITLE
ROS2 for FR3

### ISSUE THREAD

**Issue by kuyhnooj** [frankaemika/franka_ros2#22]
Sorry for poor English ;(

this ROS2 source is only for panda. So i edited all xacro and file and name 'panda' to 'fr3'.

Do you have any plan to make ROS2 source for FR3??

or

Am i right editting all panda to fr3??

**Comment by andrejpan** [comment]
Redundant issue #8 and pending PR #10.

**Comment by marcbone** [comment]
You can edit replace panda with fr3 everywhere but this does not do much. The current version works with panda and fr3 on foxy
