### ISSUE TITLE
Question: Why does the franka_ros2 implementation offer such a reduced set of functionality?

### ISSUE THREAD

**Issue by craig-sony** [frankaemika/franka_ros2#24]
Is there a technical reason why so little of the franka_ros1 functionality has been ported over to ros2? Why are only the effort controllers available?

Thanks and apologies if this is obvious/described elsewhere.

**Comment by andrejpan** [comment]
In the past, FE could not afford to put sufficient resources into supporting ROS 2. However, you can get more info about [ROS 2 Humble](https://github.com/frankaemika/franka_ros2/issues/8) port plans here.
