### ISSUE TITLE
Exposing Gravity Compensation Controller on FR3

### ISSUE THREAD

**Issue by alberthli** [frankaemika/franka_ros2#26]
Is there a way to access (or disable) Franka's gravity compensation controller running on the FR3? We are planning on swapping out the end-effector and would like that to be accurately reflected by the gravity compensation controller. We noticed that when removing the default FR3 gripper completely and trying to track a trajectory, the robot has massive overshooting, which suggests that the gravity compensation does not detect changes in the end-effector automatically. It would be useful to know how to pass this information to it.

**Comment by marcbone** [comment]
You can configure the EE settings in the web interface of the robot. There you can set the transform between the flange and then new EE as well as the inertia matrix, mass and the center of gravity of the EE.
