### ISSUE TITLE
Position/Velocity command interfaces

### ISSUE THREAD

**Issue by ghost** [frankaemika/franka_ros2#41]
Hello,
The franka_ros2 documentation mentions that position/velocity interfaces are 'coming soon' to bring feature parity with the ROS1 version. Is there a TFA for this ? Also given that currently > v0.1.0 doesn't work on Panda (due to libfranka > 9.0 not being supported), is there any plan on backporting this ?

I understand that Franka Emika has declared EOL for Panda and will not be supporting it beyond the EOY. Any information on the internal development plans would be helpful.

Thanks!

**Comment by ghost** [comment]
Wow, looks like the velocity interface has been pushed to humble 5 days back; could you please create a separate branch for Panda and backport this ?

Edit: nvm, looks like this uses new features of libfranka, so FR3 only.

**Comment by BarisYazici** [comment]
Thanks for your comment. Joint Velocity command interface is already released and joint position is in progress.

**Comment by BarisYazici** [comment]
Joint Position Command interface is also release
