### ISSUE TITLE
Best practice for ROS2 node subscribing to "/franka_state_controller/franka_states"

### ISSUE THREAD

**Issue by Olimoyo** [frankaemika/franka_ros2#6]
Hi,

I am running the Franka ROS1 packages and using a bridge to get the messages in ROS2.

If I would like to write a ROS2 python node that subscribes to the topic `/franka_state_controller/franka_states` of type `FrankaState`, what would be the best way to import this message definition and dependency? I'm trying to do the following right now:

```
from franka_msgs.msg import FrankaState
```

Thank you,
Oliver

**Comment by baslinjames** [comment]
Hello. Is there an update on reading the robot state with franka_ros2 @Olimoyo @marcbone ?

**Comment by Olimoyo** [comment]
I ended up not using ROS2 unfortunately.

**Comment by BarisYazici** [comment]
Franka robot state broadcaster is now supported default in ROS2 Humble. So you don't need the bridge now. You can access the `franka_robot_state` topic directly
