### ISSUE TITLE
No installation instruction for franka ros 2

### ISSUE THREAD

**Issue by LucasG2001** [frankaemika/franka_ros2#74]
Hello, 
on your website https://frankaemika.github.io/docs/franka_ros2.html#installation
you link to your readme, which has no instruction on the installation. 
Before there were instructions for local installation and via container.

**Comment by AndreasKuhner** [comment]
Hi @LucasG2001 ,
good catch! Thanks! We forgot to push the last changes... now it should be there - can you please confirm?

Cheers,
Andreas

**Comment by LucasG2001** [comment]
Yes it's on now, thank you!
