### ISSUE TITLE
Are there any plan to support ROS2 Humble?

### ISSUE THREAD

**Issue by CWEzio** [frankaemika/franka_ros2#8]
HI, I try to use franka_ros2 on Ubuntu 22.04, which only support ROS2 Humble. However, I encounter errors when I try to build this repo and it seems that currently ROS2 Humble is not supported. Are there any plan to support ROS2 Humble? Thank you! (I have to use Ubuntu 22.04 because my new computer hardware only supports Ubuntu 22.04, which is sad...)

**Comment by andrejpan** [comment]
Until the end of the year, support for this will not happen.

**Comment by mcbed** [comment]
Here is an as-is Humble port at PR #10

**Comment by YuLiHN** [comment]
> Here is an as-is Humble port at PR #10

Thanks for your work! A small suggestion: the executable of control_manager in humble should be **spawn** rather than **spawn.py**
https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html

**Comment by peterdavidfagan** [comment]
> Until the end of the year, support for this will not happen.

Are there plans for this year? It would be useful to know for planning purposes as some recently developed software might need to be backported to previous ROS versions if humble etc. won't be supported for another while.

**Comment by andrejpan** [comment]
In the next half a year it is highly likely there will be still no ROS2 support from FE.

**Comment by peterdavidfagan** [comment]
> In the next half a year it is highly likely there will be still no ROS2 support from FE.

Thanks for the quick response on this @andrejpan and ok understood.

**Comment by peterdavidfagan** [comment]
@mcbed thanks for your port to humble. Do you have details of the firmware and library versions you are using in order to run FER on ROS2?

**Comment by andrejpan** [comment]
A degree of more transparency. The whole company goes to 90% short-term work in the incoming week for up to 5 months. ROS 2 support will be delayed accordingly.

**Comment by peterdavidfagan** [comment]
@andrejpan @marcbone I am happy to work on updates to https://github.com/frankaemika/franka_ros2/pull/10 in order to run ROS2 Humble with the Franka.

Would it be feasible to receive high-level guidance on the steps, I will then dedicate time to implement these.

**Comment by marcbone** [comment]
Honestly, I think nobody of us had the time to try out #10, which is a shame :( . But I have no reason to think that it does not work.

**Comment by mcbed** [comment]
On my side, I do not have a Franka robot to test the code anymore but I will continue merging to PR #10 your suggestions to keep everything in one place. So do not hesitate to propose PRs to [this branch](https://github.com/mcbed/franka_ros2/tree/humble).

**Comment by peterdavidfagan** [comment]
Thanks @marcbone and @mcbed, I have started testing on the Franka we have in our lab. I was encountering errors related to ROS2 control not finding the effort command interfaces. 

It's about time for me to dig deeper into ROS2 control anyways so I will look to explore this further. I think the changes @mcbed has made are likely to work with very minor tweaks.

**Comment by cs-99** [comment]
@peterdavidfagan I encountered the same problem and sadly could not fix it as I am new to ROS2. Would be nice if you could let me know when you found a solution.

**Comment by peterdavidfagan** [comment]
Hi @cs-99, 

I am close to getting the latest JointTrajectoryController working on Humble. This controller is written to accept parameters from a yaml file the is compatible with [generate_parameter_library](https://github.com/PickNikRobotics/generate_parameter_library) ([see here](https://github.com/ros-controls/ros2_controllers/blob/5713a4149d4092eb3da30ad1d595ca15722c5294/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L59)).

I am only starting to work with the above myself and will be extremely cautious before running the controller on real hardware. Right now I plan to have a branch that I believe should be functional with the latest set of changes to ros2-control.

**Comment by cs-99** [comment]
Hi @peterdavidfagan, did you manage to get it running?

**Comment by peterdavidfagan** [comment]
Hi @cs-99, 

I did manage to get it running, the following pr contains much of the code: https://github.com/frankaemika/franka_ros2/pull/10.

**Comment by drewskoots** [comment]
@andrejpan @marcbone Are there plans to develop franka_ros2 further at all? ROS2 Foxy is going EOL soon, and it doesn't seem like there is much happening on bringing franka_ros2 to feature parity of franka_ros. Any update on the project status would be really appreciated!

**Comment by andrejpan** [comment]
The company is finally giving resources for ROS 2 development of FR3. Unofficially, the limited release for Humble should arrive in ~3 months.

**Comment by peterdavidfagan** [comment]
> The company is finally giving resources for ROS 2 development of FR3. Unofficially, the limited release for Humble should arrive in ~3 months.

This is great news. 

In the meantime if you need something asap @drewskoots I have been using the following fork which has been working fine for our Franka Emika Panda while leveraging MoveIt: https://github.com/peterdavidfagan/franka_ros2/tree/moveit_config_builder.

**Comment by BarisYazici** [comment]
@andrejpan yees. ROS 2 on its way!!

**Comment by drewskoots** [comment]
Great to hear! Thanks for that update :) @peterdavidfagan Thanks for the suggestion, upon first glance it looks very promising and like it can tide me over until official support is released!

**Comment by BarisYazici** [comment]
ROS 2 humble is supported now in the humble branch (default branch on github). Over time we will support more functionalities.
