### ISSUE TITLE
A bug: the test command of setup

### ISSUE THREAD

**Issue by winter-winter-z** [frankaemika/franka_ros2#81]
original test command missed "fr3" in "franka_moveit_config":
ros2 launch franka_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=true
It should be:
ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=true

**Comment by AndreasKuhner** [comment]
Hi @winter-winter-z ,
thanks for reporting it! We will update it with the next release :partying_face: 

Cheers,
Andreas
