### ISSUE TITLE
Moveit: trajectory is planned and executed, but Rviz doesn't display the robot final pose.

### ISSUE THREAD

**Issue by emarca96** [frankaemika/franka_ros2#86]
Doing this command, and activating moveit i can move the robot into the position i want. The motion is planned, and executed, but the robot visualized in Rviz doesn't move itself in the pose previously planned and executed successfully

```powershell
ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=true
``` 
Of course the  /franka/joint_states topic velocity and position are not updated with the current position and velocity to reach the executed pose. 

This is not the case specifying the robot ip (with the real robot connected).

**Comment by AndreasKuhner** [comment]
Hi @emarca96 ,
I guess this is expected - after all you use the `fake_hardware`. If you want that the robot is moving, you would e.g. need to use gazebo or the actual robot :smile: 

Cheers,
Andreas
